/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// 已切换到新 Supabase 项目
export const projectId = "sgxkplfbptwdohjjnlzd"

// ⚠️ 从 Supabase 控制台获取新项目的 anon key 后替换下面这行
// 路径：Project Settings → API → Project API keys → anon public
// 注意：每个项目的 anon key 不同，不能复用旧项目的！
export const publicAnonKey = "REPLACE_WITH_NEW_PROJECT_ANON_KEY"
